public class Product_one implements samsung_V2  {
    public string Display(){        
        system.debug('Display Logic for product 1');
        return null;
    }
    
    public integer Music(){
        system.debug('Music palyer logic for product 1');
        return null;
    }
    
    public string cal(){
        system.debug('Calender logic for product 1');
        return null;
    }
    
    public integer extra(){
        
        return null;
    }
}